{{ if or (not (hasKey .Values.issuer "enabled")) (.Values.issuer.enabled | default false) }}
apiVersion: cert-manager.io/v1alpha2
kind: {{ .Values.issuer.kind }}
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "app.chart" $ }}
    app.kubernetes.io/name: {{ include "app.name" $ }}
    app.kubernetes.io/instance: {{ include "app.fullname" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  {{- if .Values.issuer.selfSigned }}
  selfSigned: {}
  {{- else -}}
  acme:
    server: {{ .Values.issuer.server }}
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.issuer.secretName }}
    {{- if .Values.issuer.http01 }}
    http01: {}
    {{- end }}
    {{- with .Values.issuer.dns01 }}
    dns01:
      providers:
        - name: route53
          route53:
          region: {{ .region }}
          {{- if .accessKeyID  }}
          accessKeyID: {{ .accessKeyID  }}
          {{- end }}
          {{- if .secretAccessKey }}
          secretAccessKeySecretRef:
            name:  {{ .secretAccessKey.Name }}
            key:  {{ .secretAccessKey.Secret }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
